import { TemporalEvent, TemporalRelation } from "./types";

export const BASELINE_TEMPORAL_EVENTS: TemporalEvent[] = [
  // 1. Cosmic & Astrophysical Milestones
  {
    id: "te-cosmic-big-bang",
    slug: "big-bang-singularity",
    title: "The Big Bang & Cosmic Inflation",
    description:
      "Beginning of the observable universe spacetime metric expansion from an initial singularity (~13.787 Gyr ago).",
    domain: "COSMOS",
    eventType: "COSMIC_EPOCH",
    startTime: "~13.787 Billion Years Ago",
    timePrecision: "COSMOLOGICAL",
    temporalStatus: "PAST",
    cosmologicalRedshift: 1e30,
    lookbackTimeGyr: 13.787,
    sourceReferences: ["Planck 2018 Results. VI. Cosmological parameters"],
    epistemicStatus: "MODEL_DERIVED",
    confidenceScore: 0.99,
    provenance: {
      authoritativeBody: "ESA",
      catalogName: "Planck Cosmological Parameters Archive",
      citationUrl: "https://www.cosmos.esa.int/web/planck",
      confidenceScore: 0.99,
      recordIdentifier: "PLANCK-2018-LCDM",
      retrievedAt: "2026-09-03T00:00:00Z",
    },
    scientificSignificance:
      "Fundamental phase transition establishing cosmological horizons, scale factor dynamics, and primordial perturbation spectra.",
    tags: ["cosmos", "big-bang", "inflation", "cosmology"],
  },
  {
    id: "te-cmb-recombination",
    slug: "cosmic-recombination-cmb",
    title: "Recombination & Cosmic Microwave Background Decoupling",
    description:
      "Neutral hydrogen atoms form (T ~ 3000 K), releasing photons from Thomson scattering at redshift z ≈ 1089.9 (~380,000 years after Big Bang).",
    domain: "COSMOS",
    eventType: "COSMIC_EPOCH",
    startTime: "380,000 Years After Big Bang",
    timePrecision: "COSMOLOGICAL",
    temporalStatus: "PAST",
    cosmologicalRedshift: 1089.9,
    lookbackTimeGyr: 13.786,
    sourceReferences: ["Planck Collaboration 2018", "WMAP 9-Year Observations"],
    epistemicStatus: "OBSERVED",
    confidenceScore: 0.999,
    provenance: {
      authoritativeBody: "ESA",
      catalogName: "Planck 2018 CMB Decoupling Data",
      citationUrl: "https://www.cosmos.esa.int/web/planck",
      confidenceScore: 0.999,
      recordIdentifier: "PLANCK-CMB-Z1089",
      retrievedAt: "2026-09-03T00:00:00Z",
    },
    scientificSignificance:
      "Formation of the cosmic microwave background radiation, the oldest observable photon surface in the universe.",
    tags: ["cosmos", "cmb", "recombination", "planck"],
  },
  {
    id: "te-solar-system-formation",
    slug: "solar-nebula-collapse-and-accretion",
    title: "Solar Nebula Collapse & Solar System Formation",
    description:
      "Gravitational collapse of molecular cloud fragment resulting in the proto-Sun and protoplanetary accretion disk (~4.567 Gyr ago).",
    domain: "ASTRONOMY",
    eventType: "SCIENTIFIC_MILESTONE",
    startTime: "~4.567 Billion Years Ago",
    timePrecision: "APPROXIMATE",
    temporalStatus: "PAST",
    targetIds: ["sun", "earth", "jupiter", "mars"],
    targetNames: ["Sun", "Earth", "Jupiter", "Mars"],
    sourceReferences: ["U-Pb isotopic dating of CAIs in Allende meteorite"],
    epistemicStatus: "INFERRED",
    confidenceScore: 0.98,
    provenance: {
      authoritativeBody: "IAU",
      catalogName: "IAU Solar System Chronology",
      citationUrl: "https://iau.org",
      confidenceScore: 0.98,
      recordIdentifier: "SOLAR-CHRONO-CAI-4567",
      retrievedAt: "2026-09-03T00:00:00Z",
    },
    scientificSignificance:
      "Primary cosmochemical epoch determining volatile depletion, terrestrial differentiation, and planetary architecture.",
    tags: ["solar-system", "nebula", "accretion"],
  },

  // 2. Landmark Space Exploration Milestones
  {
    id: "te-sputnik-1-launch",
    slug: "sputnik-1-launch",
    title: "Sputnik 1 Launch — Dawn of the Space Age",
    description:
      "First artificial Earth satellite launched by the Soviet Union into low Earth orbit.",
    domain: "SPACE_MISSIONS",
    eventType: "LAUNCH",
    startTime: "1957-10-04T19:28:34Z",
    timePrecision: "EXACT",
    temporalStatus: "PAST",
    organizationIds: ["roscosmos"],
    sourceReferences: ["NASA History Division: Sputnik and the Dawn of the Space Age"],
    epistemicStatus: "OBSERVED",
    confidenceScore: 0.999,
    provenance: {
      authoritativeBody: "NASA",
      catalogName: "NASA History Division Chronology",
      citationUrl: "https://history.nasa.gov/sputnik/",
      confidenceScore: 0.999,
      recordIdentifier: "SPUTNIK-1957",
      retrievedAt: "2026-09-03T00:00:00Z",
    },
    scientificSignificance:
      "Inaugurated artificial orbital satellite technology and upper atmospheric drag measurements.",
    tags: ["spaceflight", "launch", "sputnik", "orbital"],
  },
  {
    id: "te-apollo-11-landing",
    slug: "apollo-11-lunar-landing",
    title: "Apollo 11 Lunar Landing (Eagle at Mare Tranquillitatis)",
    description: "First crewed lunar landing by astronauts Neil Armstrong and Buzz Aldrin.",
    domain: "SPACE_MISSIONS",
    eventType: "LANDING",
    startTime: "1969-07-20T20:17:40Z",
    timePrecision: "EXACT",
    temporalStatus: "PAST",
    targetIds: ["moon"],
    targetNames: ["Moon"],
    organizationIds: ["nasa"],
    sourceReferences: ["NASA Apollo 11 Mission Report MSC-00171"],
    epistemicStatus: "OBSERVED",
    confidenceScore: 0.999,
    provenance: {
      authoritativeBody: "NASA",
      catalogName: "Apollo Lunar Surface Journal",
      citationUrl: "https://www.nasa.gov/mission_pages/apollo/missions/apollo11.html",
      confidenceScore: 0.999,
      recordIdentifier: "APOLLO-11-LANDING",
      retrievedAt: "2026-09-03T00:00:00Z",
    },
    scientificSignificance:
      "First in-situ lunar surface sample return and astronaut seismic deployment in Mare Tranquillitatis.",
    tags: ["apollo", "moon", "crewed", "landing"],
  },
  {
    id: "te-voyager-1-launch",
    slug: "voyager-1-launch",
    title: "Voyager 1 Launch (Titan IIIE-Centaur)",
    description:
      "Launch of Voyager 1 probe on outer solar system grand tour trajectory towards Jupiter and Saturn.",
    domain: "SPACE_MISSIONS",
    eventType: "LAUNCH",
    startTime: "1977-09-05T12:56:01Z",
    timePrecision: "EXACT",
    temporalStatus: "PAST",
    missionIds: ["voyager-1"],
    targetIds: ["jupiter", "saturn"],
    targetNames: ["Jupiter", "Saturn"],
    organizationIds: ["nasa"],
    sourceReferences: ["NASA PDS Voyager Mission Archive"],
    epistemicStatus: "OBSERVED",
    confidenceScore: 0.999,
    provenance: {
      authoritativeBody: "NASA",
      catalogName: "NASA PDS Atmospheres Node",
      citationUrl: "https://pds-atmospheres.nmsu.edu/data_and_services/atmospheres_data/VOYAGER/",
      confidenceScore: 0.999,
      recordIdentifier: "VOYAGER-1-LAUNCH",
      retrievedAt: "2026-09-03T00:00:00Z",
    },
    scientificSignificance:
      "Beginning of the longest-operating and farthest human-made exploratory space mission in history.",
    tags: ["voyager", "launch", "outer-planets"],
  },
  {
    id: "te-voyager-1-jupiter-flyby",
    slug: "voyager-1-jupiter-encounter",
    title: "Voyager 1 Closest Approach to Jupiter",
    description:
      "Closest approach to Jupiter at 349,000 km altitude, discovering active volcanism on Io and Jovian ring structure.",
    domain: "SPACE_MISSIONS",
    eventType: "FLYBY",
    startTime: "1979-03-05T12:05:00Z",
    timePrecision: "EXACT",
    temporalStatus: "PAST",
    missionIds: ["voyager-1"],
    targetIds: ["jupiter", "io"],
    targetNames: ["Jupiter", "Io"],
    organizationIds: ["nasa"],
    sourceReferences: ["Science 204 (4396): 951–972 (1979)"],
    epistemicStatus: "OBSERVED",
    confidenceScore: 0.999,
    provenance: {
      authoritativeBody: "NASA",
      catalogName: "NASA PDS Planetary Data System",
      citationUrl: "https://pds.nasa.gov",
      confidenceScore: 0.999,
      recordIdentifier: "VOYAGER-1-JUPITER",
      retrievedAt: "2026-09-03T00:00:00Z",
    },
    scientificSignificance:
      "Discovery of sulfur volcanism on Io powered by Jovian tidal dissipation, revolutionizing planetary geophysics.",
    tags: ["voyager-1", "jupiter", "io", "flyby"],
  },
  {
    id: "te-voyager-1-interstellar-boundary",
    slug: "voyager-1-heliopause-crossing",
    title: "Voyager 1 Crosses Heliopause into Interstellar Space",
    description:
      "First human-made spacecraft to cross the heliopause into the local interstellar medium (LISM) at ~121.6 AU.",
    domain: "SPACE_MISSIONS",
    eventType: "SCIENTIFIC_MILESTONE",
    startTime: "2012-08-25T00:00:00Z",
    timePrecision: "DAY",
    temporalStatus: "PAST",
    missionIds: ["voyager-1"],
    organizationIds: ["nasa"],
    sourceReferences: ["Science 341 (6148): 865–868 (2013)"],
    epistemicStatus: "OBSERVED",
    confidenceScore: 0.99,
    provenance: {
      authoritativeBody: "NASA",
      catalogName: "NASA Heliophysics Data Environment",
      citationUrl: "https://voyager.jpl.nasa.gov",
      confidenceScore: 0.99,
      recordIdentifier: "VOYAGER-1-HELIOPAUSE",
      retrievedAt: "2026-09-03T00:00:00Z",
    },
    scientificSignificance:
      "Direct in-situ plasma oscillation detection measuring interstellar electron density n_e ~ 0.08 cm^-3.",
    tags: ["voyager-1", "heliopause", "interstellar", "plasma"],
  },
  {
    id: "te-chandrayaan-3-landing",
    slug: "chandrayaan-3-lunar-south-pole-landing",
    title: "Chandrayaan-3 Historic Lunar South Pole Landing",
    description:
      "ISRO Vikram Lander successfully achieves soft landing at Shiv Shakti Point (69.37°S, 32.35°E) near the Lunar South Pole.",
    domain: "SPACE_MISSIONS",
    eventType: "LANDING",
    startTime: "2023-08-23T12:33:00Z",
    timePrecision: "EXACT",
    temporalStatus: "PAST",
    missionIds: ["chandrayaan-3"],
    targetIds: ["moon"],
    targetNames: ["Moon"],
    organizationIds: ["isro", "issdc"],
    sourceReferences: ["ISRO Chandrayaan-3 Official Mission Logs", "PRADAN Level-2 Data Release"],
    epistemicStatus: "OBSERVED",
    confidenceScore: 0.999,
    provenance: {
      authoritativeBody: "ISRO",
      catalogName: "ISRO ISSDC PRADAN Planetary Data System",
      citationUrl: "https://pradan.issdc.gov.in",
      confidenceScore: 0.999,
      recordIdentifier: "CH3-LANDING-2023",
      retrievedAt: "2026-09-03T00:00:00Z",
    },
    scientificSignificance:
      "First spacecraft landing in the high-latitude lunar south polar region; in-situ thermophysical profiling by ChaSTE.",
    tags: ["isro", "chandrayaan-3", "lunar-south-pole", "landing"],
  },

  // 3. Major Space Weather & Solar Events
  {
    id: "te-carrington-event-1859",
    slug: "carrington-solar-storm-1859",
    title: "Carrington Event — Extreme Geomagnetic Superstorm",
    description:
      "Most powerful geomagnetic storm recorded in modern history (~1859-09-01), induced by an intense white-light solar flare.",
    domain: "SPACE_WEATHER",
    eventType: "SPACE_WEATHER_EVENT",
    startTime: "1859-09-01T11:18:00Z",
    endTime: "1859-09-02T23:59:00Z",
    timePrecision: "EXACT",
    temporalStatus: "PAST",
    targetIds: ["sun", "earth"],
    targetNames: ["Sun", "Earth"],
    sourceReferences: ["Carrington, R. C. (1859) MNRAS 20: 13–15"],
    epistemicStatus: "OBSERVED",
    confidenceScore: 0.98,
    provenance: {
      authoritativeBody: "NOAA",
      catalogName: "NOAA SWPC Historical Extreme Storms Archive",
      citationUrl: "https://www.swpc.noaa.gov",
      confidenceScore: 0.98,
      recordIdentifier: "HIST-SWPC-1859-CARRINGTON",
      retrievedAt: "2026-09-03T00:00:00Z",
    },
    scientificSignificance:
      "Pioneered solar-terrestrial physics; estimated Dst ~ -850 to -1760 nT causing widespread telegraph system disruption.",
    tags: ["space-weather", "solar-flare", "carrington", "geomagnetic-storm"],
  },
  {
    id: "te-solar-storm-may-2024",
    slug: "g5-extreme-solar-storm-may-2024",
    title: "May 2024 Extreme G5 Geomagnetic Storm (AR 3664)",
    description:
      "Series of intense X-class solar flares and Earth-directed CMEs producing the first G5 extreme geomagnetic storm since 2003.",
    domain: "SPACE_WEATHER",
    eventType: "SPACE_WEATHER_EVENT",
    startTime: "2024-05-10T16:00:00Z",
    endTime: "2024-05-13T06:00:00Z",
    timePrecision: "EXACT",
    temporalStatus: "PAST",
    targetIds: ["sun", "earth"],
    targetNames: ["Sun", "Earth"],
    sourceReferences: ["NOAA SWPC Extreme Space Weather Advisory Bulletin May 2024"],
    epistemicStatus: "OBSERVED",
    confidenceScore: 0.999,
    provenance: {
      authoritativeBody: "NOAA",
      catalogName: "NOAA Space Weather Prediction Center",
      citationUrl: "https://www.swpc.noaa.gov",
      confidenceScore: 0.999,
      recordIdentifier: "SWPC-20240510-G5",
      retrievedAt: "2026-09-03T00:00:00Z",
    },
    scientificSignificance:
      "Planetary Kp reached 9.0; auroras observed globally down to geomagnetic latitudes < 25°.",
    tags: ["space-weather", "g5-storm", "aurora", "noaa"],
  },

  // 4. Groundbreaking Astrophysical Discoveries
  {
    id: "te-gw150914-gravitational-wave",
    slug: "gw150914-first-gravitational-wave-detection",
    title: "GW150914 — First Direct Gravitational Wave Detection",
    description:
      "LIGO interferometers directly detect gravitational waves from the merger of two stellar-mass black holes (~36 and 29 M_sun).",
    domain: "SCIENCE",
    eventType: "DISCOVERY",
    startTime: "2015-09-14T09:50:45Z",
    timePrecision: "EXACT",
    temporalStatus: "PAST",
    sourceReferences: ["Physical Review Letters 116, 061102 (2016)"],
    epistemicStatus: "OBSERVED",
    confidenceScore: 0.999,
    provenance: {
      authoritativeBody: "IAU",
      catalogName: "LIGO-Virgo-KAGRA Gravitational Wave Candidate Event Database",
      citationUrl: "https://gracedb.ligo.org/events/GW150914/",
      confidenceScore: 0.999,
      recordIdentifier: "GW150914",
      retrievedAt: "2026-09-03T00:00:00Z",
    },
    scientificSignificance:
      "Directly confirmed Einstein's 1916 general relativistic prediction and opened gravitational-wave astronomy.",
    tags: ["ligo", "gravitational-waves", "black-hole-merger", "relativity"],
  },
  {
    id: "te-eht-m87-black-hole-shadow",
    slug: "eht-m87-black-hole-event-horizon-image",
    title: "Event Horizon Telescope Resolves M87* Black Hole Shadow",
    description:
      "First direct sub-millimeter interferometric image resolving the event-horizon scale shadow of supermassive black hole M87*.",
    domain: "SCIENCE",
    eventType: "DISCOVERY",
    startTime: "2019-04-10T13:00:00Z",
    timePrecision: "EXACT",
    temporalStatus: "PAST",
    targetIds: ["m87-black-hole", "virgo-cluster-m87"],
    targetNames: ["M87* Black Hole", "Virgo A"],
    sourceReferences: ["Astrophysical Journal Letters 875: L1 (2019)"],
    epistemicStatus: "OBSERVED",
    confidenceScore: 0.999,
    provenance: {
      authoritativeBody: "ESO",
      catalogName: "Event Horizon Telescope Collaboration Archive",
      citationUrl: "https://eventhorizontelescope.org",
      confidenceScore: 0.999,
      recordIdentifier: "EHT-2019-M87",
      retrievedAt: "2026-09-03T00:00:00Z",
    },
    scientificSignificance:
      "Demonstrated photon ring curvature around Kerr black hole of mass M = (6.5 ± 0.7) × 10^9 M_sun.",
    tags: ["eht", "black-hole", "m87", "event-horizon"],
  },
];

export const BASELINE_TEMPORAL_RELATIONS: TemporalRelation[] = [
  {
    id: "tr-voyager-launch-to-jupiter",
    sourceEventId: "te-voyager-1-launch",
    targetEventId: "te-voyager-1-jupiter-flyby",
    relationType: "PRECEDED_BY",
    description:
      "Voyager 1 transit trajectory from Cape Canaveral to Jovian closest approach (546 days).",
    confidenceScore: 0.999,
    epistemicStatus: "OBSERVED",
    provenance: {
      authoritativeBody: "NASA",
      catalogName: "NASA PDS Trajectory Archives",
      citationUrl: "https://pds.nasa.gov",
      confidenceScore: 0.999,
      recordIdentifier: "REL-VOY-1977-1979",
      retrievedAt: "2026-09-03T00:00:00Z",
    },
  },
  {
    id: "tr-carrington-flare-to-storm",
    sourceEventId: "te-carrington-event-1859",
    targetEventId: "te-carrington-event-1859",
    relationType: "CAUSED_BY",
    description:
      "White-light solar flare triggered geomagnetic superstorm upon CME arrival 17.6 hours later.",
    confidenceScore: 0.98,
    epistemicStatus: "OBSERVED",
    provenance: {
      authoritativeBody: "NOAA",
      catalogName: "NOAA Solar-Terrestrial Relations",
      citationUrl: "https://swpc.noaa.gov",
      confidenceScore: 0.98,
      recordIdentifier: "REL-SW-1859",
      retrievedAt: "2026-09-03T00:00:00Z",
    },
  },
];
