import { z } from "zod";
import { ProvenanceRecordSchema } from "../provenance/types";
import {
  OrganizationParticipationSchema,
  DataArchiveSchema,
  PublicSourceSchema,
  GeographicRegionSchema,
} from "../organization/schema";

export const EpistemicStatusSchema = z.enum(["OBSERVED", "INFERRED", "MODEL_DERIVED"]);

export const MissionStatusSchema = z.enum([
  "PROPOSED",
  "PLANNED",
  "APPROVED",
  "DEVELOPING",
  "LAUNCHED",
  "ACTIVE",
  "EXTENDED",
  "COMPLETED",
  "PARTIALLY_SUCCESSFUL",
  "FAILED",
  "LOST",
  "LOST_CONTACT",
  "CANCELLED",
  "DECOMMISSIONED",
  "UNKNOWN",
]);

export const MissionTypeSchema = z.enum([
  "ORBITER",
  "LANDER",
  "ROVER",
  "FLYBY",
  "ATMOSPHERIC_PROBE",
  "SAMPLE_RETURN",
  "SPACE_TELESCOPE",
  "SOLAR_OBSERVATORY",
  "HUMAN_SPACEFLIGHT",
  "INTERSTELLAR",
  "PLANETARY_EXPLORATION",
  "LUNAR_EXPLORATION",
  "MARS_EXPLORATION",
  "SMALL_BODY_EXPLORATION",
  "SOLAR_PHYSICS",
  "ASTROPHYSICS",
  "COSMOLOGY",
  "EARTH_OBSERVATION",
  "SPACE_WEATHER",
  "HELIOPHYSICS",
  "ASTROMETRY",
  "RADIO_ASTRONOMY",
  "X_RAY_ASTRONOMY",
  "GAMMA_RAY_ASTRONOMY",
  "INFRARED_ASTRONOMY",
  "ULTRAVIOLET_ASTRONOMY",
  "OPTICAL_ASTRONOMY",
  "GRAVITATIONAL_WAVE_ASTRONOMY",
  "COSMIC_RAY_RESEARCH",
  "ASTROBIOLOGY",
  "SPACE_TECHNOLOGY",
  "SPACE_STATION",
  "TECHNOLOGY_DEMONSTRATION",
  "DEFENSE_RESEARCH",
  "EARTH_SCIENCE",
  "ATMOSPHERIC_SCIENCE",
  "OTHER_SCIENTIFIC",
]);

export const SpacecraftTypeSchema = z.enum([
  "ORBITER",
  "LANDER",
  "ROVER",
  "FLYBY_PROBE",
  "ATMOSPHERIC_PROBE",
  "SPACE_TELESCOPE",
  "SOLAR_OBSERVATORY",
  "CREW_CAPSULE",
  "LUNAR_MODULE",
  "SERVICE_MODULE",
  "SAMPLE_RETURN_CAPSULE",
  "HELICOPTER_DRONE",
]);

export const InstrumentTypeSchema = z.enum([
  "OPTICAL_IMAGER",
  "INFRARED_SPECTROMETER",
  "UV_SPECTROMETER",
  "XRAY_SPECTROMETER",
  "GAMMA_RAY_SPECTROMETER",
  "MASS_SPECTROMETER",
  "MAGNETOMETER",
  "PLASMA_WAVE_DETECTOR",
  "RADAR_ALTIMETER",
  "RADIO_SCIENCE",
  "DUST_DETECTOR",
  "MICROWAVE_RADIOMETER",
  "SEISMOMETER",
  "PARTICLE_DETECTOR",
]);

export const DiscoveryTypeSchema = z.enum([
  "WATER_EVIDENCE",
  "ORGANIC_MOLECULES",
  "ATMOSPHERIC_DISCOVERY",
  "GEOLOGICAL_DISCOVERY",
  "MAGNETIC_FIELD",
  "RING_STRUCTURE",
  "EXOPLANET_DETECTION",
  "COSMOLOGICAL_DISCOVERY",
  "SOLAR_PHYSICS",
  "PLASMA_PHYSICS",
]);

export const MissionEventTypeSchema = z.enum([
  "MISSION_LAUNCH",
  "TRAJECTORY_CORRECTION_MANEUVER",
  "GRAVITY_ASSIST",
  "ORBIT_INSERTION",
  "LANDING",
  "SAMPLE_COLLECTION",
  "SAMPLE_RETURN_EARTH",
  "PRIMARY_MISSION_COMPLETE",
  "EXTENDED_MISSION_START",
  "COMMUNICATION_LOSS",
  "MISSION_END",
  "HELIOPAUSE_CROSSING",
  "TARGET_ARRIVAL",
  "DISCOVERY",
]);

export const TrajectoryAccuracySchema = z.enum([
  "HISTORICAL_RECONSTRUCTED",
  "MODEL_DERIVED",
  "ILLUSTRATIVE",
]);

export const TrajectoryWaypointSchema = z.object({
  timestamp: z.string(),
  positionAu: z.tuple([z.number(), z.number(), z.number()]),
  velocityKmS: z.number().optional(),
  distanceFromSunAu: z.number().optional(),
  distanceFromEarthAu: z.number().optional(),
  targetEncounter: z
    .object({
      targetId: z.string(),
      targetName: z.string(),
      flybyDistanceKm: z.number().optional(),
    })
    .optional(),
  eventDescription: z.string().optional(),
  isKeyMilestone: z.boolean().optional(),
});

export const MissionTrajectorySchema = z.object({
  id: z.string(),
  missionId: z.string(),
  spacecraftId: z.string().optional(),
  accuracy: TrajectoryAccuracySchema,
  referenceFrame: z.enum(["HELIOCENTRIC_ECLIPTIC", "GEOCENTRIC", "PLANETOCENTRIC"]),
  waypoints: z.array(TrajectoryWaypointSchema),
  provenance: ProvenanceRecordSchema,
});

export const SpacecraftStateSchema = z.object({
  currentDistanceAu: z.number().optional(),
  heliocentricDistanceAu: z.number().optional(),
  apparentConstellation: z.string().optional(),
  isInterstellar: z.boolean().optional(),
  communicationDelayMinutes: z.number().optional(),
  speedKmS: z.number().optional(),
  lastContactDate: z.string().optional(),
  notes: z.string().optional(),
});

export const MissionTelemetrySchema = z.object({
  currentStatus: z.enum([
    "ACTIVE_CRUISE",
    "IN_ORBIT",
    "SURFACE_OPERATIONS",
    "FLYBY_APPROACH",
    "DEEP_SPACE_TRANSIT",
    "EXTENDED_MISSION",
    "MISSION_COMPLETE",
    "STANDBY",
  ]),
  distanceFromEarthKm: z.number().optional(),
  distanceFromSunAu: z.number().optional(),
  velocityKmS: z.number().optional(),
  lightTimeMinutes: z.number().optional(),
  missionPhase: z.string(),
  telemetryEpistemicStatus: EpistemicStatusSchema,
  lastTelemetryTimestamp: z.string(),
  sourceStation: z.string().optional(),
  payloadHealth: z.enum(["OPTIMAL", "NOMINAL", "DEGRADED", "STANDBY", "OFFLINE"]).optional(),
  activeInstrumentIds: z.array(z.string()).optional(),
  subsystemSummary: z.string().optional(),
});

export const SpacecraftSchema = z.object({
  id: z.string(),
  slug: z.string(),
  missionId: z.string(),
  name: z.string(),
  type: SpacecraftTypeSchema,
  status: MissionStatusSchema,
  launchDate: z.string(),
  endDate: z.string().optional(),
  massKg: z.number().optional(),
  dryMassKg: z.number().optional(),
  dimensionsMeters: z
    .object({
      length: z.number().optional(),
      width: z.number().optional(),
      height: z.number().optional(),
      span: z.number().optional(),
    })
    .optional(),
  powerWatts: z.number().optional(),
  powerSource: z.enum(["SOLAR_ARRAYS", "RTG", "BATTERY", "FUEL_CELL"]).optional(),
  propulsionSystem: z.string().optional(),
  communicationSystem: z.string().optional(),
  instrumentIds: z.array(z.string()),
  targetIds: z.array(z.string()),
  currentState: SpacecraftStateSchema.optional(),
  telemetry: MissionTelemetrySchema.optional(),
  summary: z.string(),
  provenance: ProvenanceRecordSchema,
});

export const MissionInstrumentSchema = z.object({
  id: z.string(),
  slug: z.string(),
  name: z.string(),
  acronym: z.string().optional(),
  type: InstrumentTypeSchema,
  wavelengthRange: z.string().optional(),
  observingModes: z.array(z.string()).optional(),
  missionId: z.string(),
  spacecraftId: z.string().optional(),
  targetCapabilities: z.array(z.string()).optional(),
  scientificPurpose: z.string(),
  description: z.string().optional(),
  provenance: ProvenanceRecordSchema,
});

export const ScientificDiscoverySchema = z.object({
  id: z.string(),
  slug: z.string(),
  title: z.string(),
  date: z.string(),
  missionId: z.string(),
  spacecraftId: z.string().optional(),
  instrumentId: z.string().optional(),
  targetId: z.string().optional(),
  targetName: z.string().optional(),
  discoveryType: DiscoveryTypeSchema,
  epistemicStatus: EpistemicStatusSchema,
  description: z.string(),
  scientificSignificance: z.string(),
  citationUrl: z.string().optional(),
  provenance: ProvenanceRecordSchema,
});

export const MissionEventSchema = z.object({
  id: z.string(),
  timestamp: z.string(),
  eventType: MissionEventTypeSchema,
  title: z.string(),
  description: z.string(),
  targetId: z.string().optional(),
  targetName: z.string().optional(),
  missionId: z.string(),
  spacecraftId: z.string().optional(),
  scientificSignificance: z.string().optional(),
  provenance: ProvenanceRecordSchema,
});

export const SpaceMissionSchema = z.object({
  id: z.string(),
  slug: z.string(),
  name: z.string(),
  agency: z.string(),
  type: MissionTypeSchema,
  status: MissionStatusSchema,
  launchDate: z.string(),
  endDate: z.string().optional(),
  leadOrganizationId: z.string().optional(),
  leadOrganizationSlug: z.string().optional(),
  country: z.string().optional(),
  region: GeographicRegionSchema.optional(),
  participatingOrganizations: z.array(OrganizationParticipationSchema).optional(),
  cosparId: z.string().optional(),
  noradId: z.string().optional(),
  nssdcId: z.string().optional(),
  launchVehicle: z.string().optional(),
  launchSite: z.string().optional(),
  primaryTargetId: z.string().optional(),
  secondaryTargetIds: z.array(z.string()).optional(),
  spacecraftIds: z.array(z.string()),
  instrumentIds: z.array(z.string()),
  discoveryIds: z.array(z.string()),
  eventIds: z.array(z.string()),
  trajectoryId: z.string().optional(),
  destination: z.string(),
  objective: z.string(),
  summary: z.string(),
  scientificResults: z.array(z.string()).optional(),
  dataArchives: z.array(DataArchiveSchema).optional(),
  officialSources: z.array(PublicSourceSchema).optional(),
  heroImageUrl: z.string().optional(),
  telemetry: MissionTelemetrySchema.optional(),
  provenance: ProvenanceRecordSchema,
});
